"""Independent Gerbonara parsing of X2 Gerbers/Excellon versus routed source.
Checks layer inventory, pad net/coordinates, all drill hits, BOM and placement.
"""
import argparse
from collections import Counter
import csv
import hashlib
import json
import math
from pathlib import Path
import warnings
import xml.etree.ElementTree as ET
from gerbonara import LayerStack,ExcellonFile
from gerbonara.utils import MM
from sexp import parse,find,find_all

ROOT=Path(__file__).resolve().parents[1]
def main():
 parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--release',type=Path,default=ROOT/'output/release-candidate');a=parser.parse_args();out=a.release
 pcb=ROOT/'wpc_power_driver_cost.kicad_pcb';board=parse(pcb.read_text())[0];pads={};holes={'PTH':Counter(),'NPTH':Counter()};failures=[];checks=0
 def check(ok,message):
  nonlocal checks
  checks+=1
  if not ok:failures.append(message)
 def position(fp,pad):
  x,y,*angle=map(float,find(fp,'at')[1:]);theta=math.radians(angle[0] if angle else 0);px,py=map(float,find(pad,'at')[1:3]);return (x+px*math.cos(theta)+py*math.sin(theta),y-px*math.sin(theta)+py*math.cos(theta))
 def hit(x,y,d):return (round(x,4),round(y,4),round(d,4))
 for fp in find_all(board,'footprint'):
  props={p[1]:p[2] for p in find_all(fp,'property')};ref=props['Reference']
  for pad in find_all(fp,'pad'):
   x,y=position(fp,pad);net=find(pad,'net');layers=find(pad,'layers')[1:]
   if net and pad[1]:pads[(ref,pad[1],round(x,4),round(y,4))]={'net':net[-1],'layers':layers}
   if pad[2] in ('thru_hole','np_thru_hole'):
    drill=find(pad,'drill');assert len(drill)==2,'Slotted drill needs explicit checking';holes['PTH' if pad[2]=='thru_hole' else 'NPTH'][hit(x,y,float(drill[1]))]+=1
 for via in find_all(board,'via'):
  x,y=map(float,find(via,'at')[1:3]);holes['PTH'][hit(x,y,float(find(via,'drill')[1]))]+=1
 with warnings.catch_warnings(record=True) as caught:
  warnings.simplefilter('always');stack=LayerStack.open(out/'gerbers');drill_counts={}
  for kind in ('PTH','NPTH'):
   files=list((out/'drill').glob('*-'+kind+'.drl'));check(len(files)==1,kind+' drill inventory');d=ExcellonFile.open(files[0]);actual=Counter(hit(o.x,-o.y,o.aperture.diameter) for o in d.objects)
   check(actual==holes[kind],kind+' drill geometry differs: '+str({'missing':list((holes[kind]-actual).items())[:8],'extra':list((actual-holes[kind]).items())[:8]}));drill_counts[kind]=sum(actual.values())
   if kind=='PTH':stack.drill_pth=d
   else:stack.drill_npth=d
  layer_map={('top','copper'):'F.Cu',('inner_1','copper'):'In1.Cu',('inner_2','copper'):'In2.Cu',('bottom','copper'):'B.Cu'}
  expected=set(layer_map)|{(s,k) for s in ('top','bottom') for k in ('mask','silk','paste')}|{('mechanical','outline')}
  check(set(stack.graphic_layers)==expected,'Gerber layer inventory')
  found={};counts={}
  by_component_position={}
  for key in pads:by_component_position.setdefault((key[0],key[2],key[3]),[]).append(key)
  for layer,physical in layer_map.items():
   gerber=stack.graphic_layers[layer];counts[physical]=len(gerber.objects);seen=set()
   for obj in gerber.objects:
    attr=obj.attrs if isinstance(obj.attrs,dict) else {};pin=attr.get('.P')
    if not hasattr(obj,'x'):continue
    x,y=round(obj.x,4),round(-obj.y,4)
    if pin and len(pin)>=2:keys=[(pin[0],pin[1],x,y)]
    elif attr.get('.C'):keys=by_component_position.get((attr['.C'][0],x,y),[])
    else:continue
    # KiCad emits .C plus .N for inner-layer PTH flashes, .P on outer layers.
    for key in keys:
     if key not in pads:continue # unnetlisted/mechanical pads assessed by native DRC
     seen.add(key);check(attr.get('.N',(None,))[0]==pads[key]['net'],f'{physical} {key} Gerber net mismatch')
   for key,pad in pads.items():
    if physical in pad['layers'] or '*.Cu' in pad['layers']:check(key in seen,f'{physical}: missing Gerber pad {key}')
   found[physical]=len(seen)
  # SVG views are generated by the independent parser, with actual drill files.
  for side in ('top','bottom'):
   (out/'reports'/f'gerber-{side}.svg').write_text(str(stack.to_svg(side_re=side+'|mechanical',drills=True)))
 warning_text=sorted(set(str(w.message) for w in caught))
 bounds=stack.board_bounds();width=bounds[1][0]-bounds[0][0];height=bounds[1][1]-bounds[0][1]
 # Bounds include the 0.1 mm plotted Edge.Cuts stroke. The routing centreline is the cut contour.
 check(abs((width-.1)-449.152)<.001 and abs((height-.1)-272.910)<.001,'Unexpected routed outline dimensions')
 xml=ET.parse(out/'reports/netlist.xml');components={c.attrib['ref']:c for c in xml.findall('.//components/comp')}
 rows=list(csv.DictReader((out/'bom/all-components.csv').open()));indexed={r['Designator']:r for r in rows}
 for ref,c in components.items():
  if ref.startswith('H'):continue
  check(ref in indexed,ref+' absent from assembly BOM')
  if ref not in indexed:continue
  row=indexed[ref];fields={f.attrib['name']:f.text or '' for f in c.findall('fields/field')}
  for key,value in [('Value',c.findtext('value')),('Footprint',c.findtext('footprint')),('MPN',fields.get('MPN',''))]:check(row[key]==value,ref+' BOM '+key+' mismatch')
  check(bool(row['DNP'])==(ref.startswith('TP') or any(p.attrib.get('name')=='dnp' for p in c.findall('property'))),ref+' DNP mismatch')
 positions=list(csv.DictReader((out/'assembly/positions.csv').open()))
 check(len({p['Ref'] for p in positions})==len(positions),'Duplicate placement references')
 for pos in positions:
  if pos['Ref'] in components:check(not any(p.attrib.get('name')=='dnp' for p in components[pos['Ref']].findall('property')),'DNP in placement '+pos['Ref'])
 report=dict(passed=not failures,checks=checks,failures=failures,pcb_sha256=hashlib.sha256(pcb.read_bytes()).hexdigest(),gerber_pad_instances=found,copper_object_counts=counts,drill_counts=drill_counts,outline_centerline_mm=[width-.1,height-.1],parser_warnings=warning_text,
             limitations='X2 attributes/pad positions and drills checked independently; does not independently solve connectivity of every plotted copper region or replace fabricator DFM/electrical testing. Native KiCad DRC provides geometric connectivity checks.')
 (out/'reports/manufacturing-check.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2));return 0 if report['passed'] else 1

if __name__=='__main__':raise SystemExit(main())
